### ISSUE TITLE
Flag IE support for opacity

### ISSUE THREAD

**Issue by KittyGiraudel** [Cyber-Duck/hoisin.scss#10]
You include IE filters in the opacity mixin. I suggest you make it easy to enable/disable with a flag:

``` scss
@mixin opacity($opac, $ie: false) {
    @if $ie {
      filter: alpha(opacity=$opac * 100);
      -ms-filter: alpha(opacity=$opac * 100);
    }
    -moz-opacity: $opac;
    -webkit-opacity: $opac;
    opacity: $opac;
}
```
