### ISSUE TITLE
Invalid placeholder mixin

### ISSUE THREAD

**Issue by KittyGiraudel** [Cyber-Duck/hoisin.scss#6]
You cannot make a single CSS selector when there are proprietary selectors invalid. Whenever you write `::-webkit-whatever, ::-moz-whatever`, it results in a failure for every browser because Webkit-based browsers do not know what `moz` means and Gecko browsers do not know what `webkit` stands for.

Fix:

``` scss
@mixin placeholder($color) {
    ::-webkit-input-placeholder {
        color: $color;
    }
    :-moz-placeholder {
        color: $color; 
    }
    :-ms-input-placeholder {
        color: $color;
    }
}
```
