### ISSUE TITLE
Heavy transform mixin

### ISSUE THREAD

**Issue by KittyGiraudel** [Cyber-Duck/hoisin.scss#7]
While I think it's a good idea to add the ability to declare the `transform-origin` property within the same mixin as `transform`, I think it should be declared when it equals the default value.

``` scss
@mixin rotate($deg, $orig: 50% 50%) {
    -o-transform: rotate(#{$deg});
    -ms-transform: rotate(#{$deg});
    -moz-transform: rotate(#{$deg});
    -webkit-transform: rotate(#{$deg});
    transform: rotate(#{$deg});

    @if $orig != 50% and $orig != (50% 50%) 
    and $orig != center and $orig != (center center) {
      -webkit-transform-origin: $orig;
      -moz-transform-origin: $orig;
      -ms-transform-origin: $orig;
      -o-transform-origin: $orig;
      transform-origin: $orig;
    }
}
```
