### ISSUE TITLE
Add default value to transition

### ISSUE THREAD

**Issue by KittyGiraudel** [Cyber-Duck/hoisin.scss#9]
From my own experience, it has occurred to me I often use the same transition across an entire project so I suggest you add a default value to the transition mixin.

I feel like `all 0.15s ease 0s` is a good one. Thankfully it can be shortened to `.15s`.

``` scss
@mixin transition($value: .15s) {
    -o-transition: $value;
    -moz-transition: $value;
    -webkit-transition: $value;
    transition: $value;
}
```

This makes it possible to use it like this:

``` scss
.element {
  @include transition;
}
```

Edit: by the way, I feel like the `transition-dur` mixin has no point whatsoever.
